### ISSUE TITLE
Create Docker development enviroment

### ISSUE THREAD

**Issue by fsherratt** [fsherratt/upgraded-parakeet#1]

**Comment by fsherratt** [comment]
Created a new branch for this [feature/docker](https://github.com/fsherratt/upgraded-parakeet/tree/feature/docker)

**Comment by Neoxas** [comment]
Following our chat, are we going to both with this?

**Comment by fsherratt** [comment]
[Hardware devices in containers Windows](https://docs.microsoft.com/en-us/virtualization/windowscontainers/deploy-containers/hardware-devices-in-containers)

**Comment by fsherratt** [comment]
> Following our chat, are we going to both with this?

Yes we're both going to work on this

**Comment by fsherratt** [comment]
In Ubuntu to get real sense devices to enumerate need to map `/dev` using `-v /dev:/dev`. Once enumerated this option is no longer needed. Would also be fixed if by installing real-sense outside of the virtualisation.

**Comment by fsherratt** [comment]
@Neoxas add in rabbit MQ stuff to this

**Comment by fsherratt** [comment]
@Neoxas I added this to the docker file and it successfully installed rabbit MQ. Is this correct?

> RUN apt-get update -y && \
>      apt-get install curl gnupg dirmngr -y && \
> 	curl -fsSL https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc | sudo apt-key add - && \
> 	apt-get install apt-transport-https erlang -y && \
> 	apt-get install rabbitmq-server -y --fix-missing

**Comment by fsherratt** [comment]
I've just noticed that I started writing some docker documentation ages ago 9ef216d640fb4b08bbc6172600dd9d843f80f780, I didn't get very far.
