### ISSUE TITLE
Write telemetry module

### ISSUE THREAD

**Issue by Neoxas** [fsherratt/upgraded-parakeet#10]
This needs to act as a simple fire and forget for forwarding info to the ground. 
Bonus points if it does recieve as well.
Might want to put them in seperate modules for speed.
Follow the standard pattern in use.

**Comment by fsherratt** [comment]
[Python webcam stream over Udp socket](https://stackoverflow.com/a/46915452)

**Comment by Neoxas** [comment]
I've got the first half of this working on the udp branch
This should be a pretty nice pattern to follow, and actually extensible to use on the rover etc.
I was going to use a differnet port for each module so it can send seperately.
Might be worth looking at some discovery methods

**Comment by Neoxas** [comment]
Fully working on udp_proxy branch. Need to write unit tests.
