### ISSUE TITLE
Function cv2.imshow not working. Requires modification to docker file

### ISSUE THREAD

**Issue by fsherratt** [fsherratt/upgraded-parakeet#13]
Just got this error while trying to run the imshow command in cv2. Will update docker file accordingly

`Exception has occurred: error
OpenCV(4.2.0) /opencv-4.2.0/modules/highgui/src/window.cpp:651: error: (-2:Unspecified error) The function is not implemented. Rebuild the library with Windows, GTK+ 2.x or Cocoa support. If you are on Ubuntu or Debian, install libgtk2.0-dev and pkg-config, then re-run cmake or configure script in function 'cvShowImage'`.

[How to include libgtk2.0-dev and pkg-config in cmake when installing openCV on Ubuntu 16](https://stackoverflow.com/questions/42843316/how-to-include-libgtk2-0-dev-and-pkg-config-in-cmake-when-installing-opencv-on-u)
- [ ] Test and close

**Comment by fsherratt** [comment]
Added ` apt-get install libgtk2.0-dev` and `-D WITH_GTK=ON` cmake option to open cv install. Also had to run `xhost +` in the host operating system. Imshow now displays an images as expected

**Comment by fsherratt** [comment]
Still getting this error, when using imshow

> Gtk-WARNING **: 14:27:35.023: Locale not supported by C library.
        Using the fallback 'C' locale.
Gtk-Message: 14:27:35.025: Failed to load module "canberra-gtk-module"

**Comment by fsherratt** [comment]
Install `libcanberra-gtk-module` and `libcanberra-gtk3-module` to fix canberra warning

**Comment by fsherratt** [comment]
Install `language-pack-en-base` and run `dpkg-reconfigure locales` to fix locale warning

**Comment by fsherratt** [comment]
Fix in 512b49914e6fe829e303a8b9f9adc8dd4a3dd841. 

Will close once @Neoxas has tested, instructions on docker launch arguments here https://github.com/fsherratt/upgraded-parakeet/issues/14#issuecomment-615338676

**Comment by Neoxas** [comment]
I'll try to test it this weekend

**Comment by Neoxas** [comment]
Work went mental. Cried a lot. Will aim to get to it

**Comment by fsherratt** [comment]
Tested in a virtual box and vmWare linux install. Worked fine in both so going to close this issue
