### ISSUE TITLE
Realsense D435/T265 Modules

### ISSUE THREAD

**Issue by fsherratt** [fsherratt/upgraded-parakeet#14]
Create modules hardware abstraction modules for Intel Realsense D435 and T265 modules. [Previous Work](https://github.com/fsherratt/ERL_SmartCities_2019/tree/master/modules/realsense)

**Comment by fsherratt** [comment]
512b49914e6fe829e303a8b9f9adc8dd4a3dd841 has a minimal working example. 

Requires the following arguments when initialising docker `-v /dev:/dev -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY:$DISPLAY --privileged`

`xhost +` must also be run in the host operating system

**Comment by Neoxas** [comment]
Can I do it without docker :P

**Comment by fsherratt** [comment]
Why would you want to do that?

**Comment by fsherratt** [comment]
Last thing to do is integrate with rabbit mq

**Comment by fsherratt** [comment]
Going to look at making this async. The big question - can the RGB and depth frames be requested independently
