### ISSUE TITLE
Define module interfaces

### ISSUE THREAD

**Issue by fsherratt** [fsherratt/upgraded-parakeet#3]

**Comment by Neoxas** [comment]
Key one to focus on right now is the camera data for the T225 and D435.
Lets just ram it into some yaml structure and see what happens.
@fsherratt Can you send me 2 minutes worth of GPS data please

**Comment by fsherratt** [comment]
We should define all the data packets using named tuples. A really elegant format is shown here [C-like structures in Python](https://stackoverflow.com/a/45426493), [typing.NamedTuple](https://docs.python.org/3/library/typing.html#typing.NamedTuple)

**Comment by fsherratt** [comment]
I've now implemented this here _[modules/data_types.py](https://github.com/fsherratt/upgraded-parakeet/blob/feature/realsense/modules/data_types.py)_ and tested in on the realsense code 6fb6277c7f33e0484ab54e246924fc237d75785f. It works great! Going to close this issue
