### ISSUE TITLE
Implement config methods for different operating modes 

### ISSUE THREAD

**Issue by fsherratt** [fsherratt/upgraded-parakeet#4]
Repeatable and change tracked configurations. 

Need to allow for SITL, HITL and deployed configurations

Probably want to put all tune-able model parameters in config files so they're easy to find. With a `.yaml` file this would also allow documentation to be put along side them

**Comment by Neoxas** [comment]
Following our chat, I take it we are just gonna use omega conf rather than hydra

**Comment by fsherratt** [comment]
[OmegaConf Documentation](https://omegaconf.readthedocs.io/en/latest/)

**Comment by fsherratt** [comment]
[YAML Tutorial](https://www.tutorialspoint.com/yaml/index.htm)

**Comment by fsherratt** [comment]
Tested in e5de53479fe125095c031a6aeeb4cdaafadb982e

**Comment by fsherratt** [comment]
Implemented here -  will be implemented in all future methods 190ac84
