### ISSUE TITLE
Setup standard unit testing template

### ISSUE THREAD

**Issue by fsherratt** [fsherratt/upgraded-parakeet#5]

**Comment by fsherratt** [comment]
Pull request #7 contains the standard template. Will close after testing while developing issue #9

**Comment by fsherratt** [comment]
[Coverage.py](https://coverage.readthedocs.io/en/latest/) python code coverage analysis

**Comment by fsherratt** [comment]
Coverage.py is very simple to use. So the final python packages will be `unittest` _(built in)_ `pytest` _(built in)_ and `coverage.py` _(need to install)_

**Comment by fsherratt** [comment]
I'd like to add a githooks to run unittests as a pre-commit action. [Pre-commit pip module ](https://pre-commit.com/), [Two Ways to Share Git Hooks with Your Team](https://www.viget.com/articles/two-ways-to-share-git-hooks-with-your-team/)

**Comment by Neoxas** [comment]
Im happy with that
I would think 80% is good coverage to aim for
