### ISSUE TITLE
2 minutes of data from T265

### ISSUE THREAD

**Issue by Neoxas** [fsherratt/upgraded-parakeet#8]
Can someone please send me/upload 2 minutes of data stream from this please.
The same for the  D435 would also be helpful

**Comment by fsherratt** [comment]
I've created 45 seconds of 60FPS data, just need to work out how best to share it with you. It's quite a large file...

Once extracted you can get the pickled data out of it, with this snippet. The data is an array of tuples. The tuple is formed of (XYZ Position, Quaternion Rotation, Tracking Confidence, Raw depth frame data, Raw RGB image data) all as numpy arrays.

```python
import pickle
with open('test.file', 'rb') as f:
    data = pickle.load(f)
```

**Comment by fsherratt** [comment]
OK, google is taking the heavy lifting for this one [test.file.tar.xz](https://drive.google.com/file/d/189MgnI9UVa1rHidK0ZCWKS17UMi_9hBE/view?usp=sharing)

**Comment by fsherratt** [comment]
Closing as this is no longer needed
