### ISSUE TITLE
Write logging module

### ISSUE THREAD

**Issue by Neoxas** [fsherratt/upgraded-parakeet#9]
A logging module with differnet levels of verbosity would be very handy.
It should follow the generic rabbit mq structure for them.
And example of this can be found here:
https://www.rabbitmq.com/tutorials/tutorial-four-python.html

**Comment by fsherratt** [comment]
![IMG_20200412_170048__01](https://user-images.githubusercontent.com/13890746/79073599-6575ed80-7cdf-11ea-9c9c-c06cd74a487c.jpg)

@Neoxas What do we think of this? Callback function that sticks new log items into a logging queue and sets a threading flag/event. A separate logging thread listens for the queue flag, grabs the data from the queue and writes to file. Clearing the flag when if queue is empty

**Comment by fsherratt** [comment]
The built-in threading package has a nice event system built in [threading.Event](https://docs.python.org/2/library/threading.html#threading.Event)

**Comment by fsherratt** [comment]
![IMG_20200413_164226](https://user-images.githubusercontent.com/13890746/79134582-dd0e5000-7da5-11ea-9f49-58bbc0876452.jpg)

Flow diagram

**Comment by fsherratt** [comment]
Converted this to pseudo-code ba6031812665ede0d5114271266296437d41964d

**Comment by Neoxas** [comment]
Only comment is you can deal with the verbosity level through rabbitmq. Shall I add the rabbitmq items to deal with message callback in the data_logger.py module or are we going to use this as an interface for another module?

**Comment by fsherratt** [comment]
`logging_interface` will be the abstract class. The `save_to_file` function will be overloaded depending on the incoming data type

**Comment by fsherratt** [comment]
Code i've written before for UDP [mavSocket.py](https://github.com/fsherratt/MAVLinkThread/blob/master/mavlinkThread/mavSocket.py)

**Comment by fsherratt** [comment]
Need to add config/setup methods to this

**Comment by fsherratt** [comment]
Useful link: [Good logging practice in Python](https://fangpenlin.com/posts/2012/08/26/good-logging-practice-in-python/)

**Comment by fsherratt** [comment]
[threading.Condition vs threading.Event](https://stackoverflow.com/questions/7424590/threading-condition-vs-threading-event) @Neoxas thoughts on which one we should use. 

Also retrieved my Linux book today, it had this to say 
![IMG_20200417_172657](https://user-images.githubusercontent.com/13890746/79592170-853b5600-80d1-11ea-8874-b0a979673892.jpg)

**Comment by fsherratt** [comment]
[Use assertLogs to test Python logs ](https://dev.to/toti1212/use-assertlogs-to-test-python-logs-43j5)
